travis:
  secure:
    BINSTAR_TOKEN: tLT0kqLYJTs1WrmD/j5pM5ECjNSYWf0s5g1Gf6jNpBmQb19yFGvjOf7cQpmuve0xx/z0HG9zCrhQwzhC7j/sn/zfdmBekllRGlsTmDFgJjpKZ9n13Y6ymo7nSwKZBxiWDCdxN3eDNfztGxcy61E6BKNmw4UY++GxnAnTbavt16wM7w/4cMK+F91Gzl+RDmin5edOA3u6HNVzFSYz/uKrNzttVZG6bH4UlTvbv1kCA/69IVdh2VmotGUQEIQDpm449NAEcAEG8E7sqy0B7hqKiEIdlp+NvZr4QI2jYm4xRlH1P/3llPEWyiU8r9VUw79d8DC+m0iF5MxFtd5BYQA3TR71eWKHQ4k73R7wO89IXBPhTcud+BrJowljm2czU9sGFhIgPxJtk/A23ssw7T7arRkwOF71lIsXylUkBWi5ApX/nQ/pRakDHA0OvSkEQGGeswSxFrGEg/QFVitBs/QN0h+ILHCFSMGigjvfezS82IOjiEEgw/JZM5olMxB3rpacB5BpoIY4pop6yh5vZtLlYFx37RAekioK+/jHLylU9mBSVRIW1dSc00pKCfEQf8lea9SfHAecsaQvOOpRqF2WqxD7s53cNpUqMVbQR+Vt+Vs0OTVx4W6T/nO1Qnyut+zfi/HUMs7DMpugvu65S+tQMhTKSkFxVq8OYMIlg4m5aDE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
